services:
  app:
    build: .
    depends_on:
      - es
    restart: always
    networks:
      - frontend
      - backend

  es:
    image: elasticsearch:2.3.0
    restart: always
    networks:
      - backend

  nginx:
    image: nginx
    volumes:
      - $PWD/flask-app/templates:/usr/share/nginx/html
      - $PWD/flask-app/static:/usr/share/nginx/html/static
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - es
    restart: always
    networks:
      - frontend
   

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge